import { Router } from "express";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import settingsRouter from "./settings";
import analyticsRouter from "./analytics";
import paymentRouter from "./payment";
import setupRouter from "./setup";
import contentRouter from "./content";
import blogRouter from "./blog";
import specialMessagesRouter from "./special-messages";
import questionsAdminRouter from "./questions-admin";
import customersAdminRouter from "./customers-admin";
import domainScansAdminRouter from "./domain-scans-admin";
import isrRouter from "./isr";

const router = Router();
router.use(authRouter);
router.use(tenantsRouter);
router.use(settingsRouter);
router.use(analyticsRouter);
router.use(paymentRouter);
router.use(setupRouter);
router.use(contentRouter);
router.use(blogRouter);
router.use(specialMessagesRouter);
router.use(questionsAdminRouter);
router.use(customersAdminRouter);
router.use(domainScansAdminRouter);
router.use(isrRouter);

export default router;
