import { Router } from "express";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import settingsRouter from "./settings";
import analyticsRouter from "./analytics";
import paymentRouter from "./payment";
import setupRouter from "./setup";
import contentRouter from "./content";
import blogRouter from "./blog";
import specialMessagesRouter from "./special-messages";
import questionsAdminRouter from "./questions-admin";
import customersAdminRouter from "./customers-admin";
import domainScansAdminRouter from "./domain-scans-admin";
import isrRouter from "./isr";
import emailTemplatesRouter from "./email-templates";
import partnersAdminRouter from "./partners";
import apiKeysAdminRouter from "../v1/admin";
import expertReviewRouter from "./expert-review";
import remediationAdminRouter from "./remediation";
import cloudCspmAdminRouter from "./cloud-cspm";
import codeSecretsAdminRouter from "./code-secrets";
import observabilityAdminRouter from "./observability";
import dnsMonitorAdminRouter from "./dns-monitor";
import ctMonitorAdminRouter from "./ct-monitor";
import ms365AdminRouter from "./ms365";
import kvkkAdminRouter from "./kvkk";
import serviceNowAdminRouter from "./servicenow";
import serviceCatalogAdminRouter from "./service-catalog";
import serviceOnboardingRouter from "./service-onboarding";
import leadDiscoveryRouter from "./lead-discovery";
import techStackRouter from "./tech-stack";
import intelligenceRouter from "./intelligence";
import cronRouter from "./cron";
import cveAdminRouter from "./cve-admin";
import musteriProvizyonRouter from "./musteri-provizyon";
import adminsRouter from "./admins";
import iocControlsRouter from "./ioc-controls";
import ctiIntelRouter from "./cti-intel";
import indexReportsRouter from "./index-reports";
import badgeAdminRouter from "./badge-admin";
import partnerLeadsAdminRouter from "./partner-leads-admin";
import sourceStatsRouter from "./source-stats";
import cyberRiskReportsRouter from "./cyber-risk-reports";
import reputationRouter from "./reputation";
import brandMonitorRouter from "./brand-monitor";
import executiveReportsRouter from "./executive-reports";
import dataLeakageRouter from "./data-leakage";

const router = Router();
router.use(authRouter);
router.use(tenantsRouter);
router.use(settingsRouter);
router.use(analyticsRouter);
router.use(paymentRouter);
router.use(setupRouter);
router.use(contentRouter);
router.use(blogRouter);
router.use(specialMessagesRouter);
router.use(questionsAdminRouter);
router.use(customersAdminRouter);
router.use(domainScansAdminRouter);
router.use(isrRouter);
router.use(emailTemplatesRouter);
router.use(partnersAdminRouter);
router.use(apiKeysAdminRouter);
router.use(expertReviewRouter);
router.use(remediationAdminRouter);
router.use(cloudCspmAdminRouter);
router.use(codeSecretsAdminRouter);
router.use(observabilityAdminRouter);
router.use(dnsMonitorAdminRouter);
router.use(ctMonitorAdminRouter);
router.use(ms365AdminRouter);
router.use(kvkkAdminRouter);
router.use(serviceNowAdminRouter);
router.use(serviceCatalogAdminRouter);
router.use(serviceOnboardingRouter);
router.use(leadDiscoveryRouter);
router.use(techStackRouter);
router.use(intelligenceRouter);
router.use(cronRouter);
router.use(cveAdminRouter);
router.use(musteriProvizyonRouter);
router.use(adminsRouter);
router.use(iocControlsRouter);
router.use(ctiIntelRouter);
router.use(indexReportsRouter);
router.use(badgeAdminRouter);
router.use(partnerLeadsAdminRouter);
router.use(sourceStatsRouter);
router.use(cyberRiskReportsRouter);
router.use(reputationRouter);
router.use(brandMonitorRouter);
router.use(executiveReportsRouter);
router.use(dataLeakageRouter);

// ─── POST /api/admin-panel/reports/annual/generate ────────────────────────────
router.post("/reports/annual/generate", async (req, res) => {
  try {
    const year: number = Number(req.body?.year) || new Date().getFullYear() - 1;
    const domain: string | undefined = req.body?.domain ?? undefined;
    const { generateAnnualReports } = await import("../../lib/reports/annualReportSvg.js");
    const sent = await generateAnnualReports(year, domain);
    res.json({ success: true, sent, year, domain: domain ?? "all" });
  } catch (err) {
    res.status(500).json({ error: String(err) });
  }
});

export default router;
