import { Router } from "express";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import settingsRouter from "./settings";
import analyticsRouter from "./analytics";
import paymentRouter from "./payment";
import setupRouter from "./setup";
import contentRouter from "./content";
import blogRouter from "./blog";
import specialMessagesRouter from "./special-messages";
import questionsAdminRouter from "./questions-admin";
import customersAdminRouter from "./customers-admin";
import domainScansAdminRouter from "./domain-scans-admin";
import isrRouter from "./isr";
import emailTemplatesRouter from "./email-templates";
import partnersAdminRouter from "./partners";
import apiKeysAdminRouter from "../v1/admin";
import expertReviewRouter from "./expert-review";
import remediationAdminRouter from "./remediation";
import cloudCspmAdminRouter from "./cloud-cspm";
import codeSecretsAdminRouter from "./code-secrets";
import observabilityAdminRouter from "./observability";
import dnsMonitorAdminRouter from "./dns-monitor";
import ctMonitorAdminRouter from "./ct-monitor";

const router = Router();
router.use(authRouter);
router.use(tenantsRouter);
router.use(settingsRouter);
router.use(analyticsRouter);
router.use(paymentRouter);
router.use(setupRouter);
router.use(contentRouter);
router.use(blogRouter);
router.use(specialMessagesRouter);
router.use(questionsAdminRouter);
router.use(customersAdminRouter);
router.use(domainScansAdminRouter);
router.use(isrRouter);
router.use(emailTemplatesRouter);
router.use(partnersAdminRouter);
router.use(apiKeysAdminRouter);
router.use(expertReviewRouter);
router.use(remediationAdminRouter);
router.use(cloudCspmAdminRouter);
router.use(codeSecretsAdminRouter);
router.use(observabilityAdminRouter);
router.use(dnsMonitorAdminRouter);
router.use(ctMonitorAdminRouter);

export default router;
