export const SECTORS = [
  "Perakende/Ticaret",
  "Üretim/Sanayi",
  "Sağlık",
  "Finans/Sigorta",
  "Eğitim",
  "Hizmet Sektörü",
  "Teknoloji",
  "Diğer"
];

export const EMPLOYEE_COUNTS = [
  "1-10",
  "11-50",
  "51-250",
  "250+"
];

export const MINI_ASSESSMENT_SECTIONS = [
  {
    id: "A",
    title: "Yönetişim ve Organizasyon",
    enTitle: "Governance & Organization",
    questions: [
      {
        id: 1,
        text: "Şirketinizde siber güvenlikten sorumlu atanmış bir kişi var mı?",
        enText: "Has your company designated a person responsible for cybersecurity?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Bu kişi IT çalışanı olmak zorunda değil. \"Bir sorun çıkarsa kim arar?\" sorusunun cevabını bilen biri yeterli.",
        enHelpText: "This person doesn't need to be an IT professional. Someone who knows the answer to 'Who do we call if something goes wrong?' is enough.",
      },
      {
        id: 2,
        text: "Şirketinizde kullanılan sistemler, yazılımlar ve hassas verilerin nerede tutulduğu listelenmiş mi?",
        enText: "Have the systems, software, and sensitive data locations used by your company been inventoried?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Müşteri bilgisi, personel verisi, finansal kayıtlar hangi programda veya bilgisayarda duruyor? Bunu biliyor musunuz?",
        enHelpText: "Where is customer information, personnel data, and financial records stored? Do you know which program or computer holds this?",
      },
    ]
  },
  {
    id: "B",
    title: "Kimlik ve Erişim Yönetimi",
    enTitle: "Identity & Access Management",
    questions: [
      {
        id: 3,
        text: "Çalışanlar e-posta ve iş uygulamalarına girerken SMS kodu veya telefon onayı (2FA) kullanıyor mu?",
        enText: "Do employees use an SMS code or phone confirmation (2FA) when logging into email and work applications?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Sadece şifre yetmiyor. \"Girişi onayla\" gibi ek bir adım, hesap ele geçirilmesini çok zorlaştırır.",
        enHelpText: "A password alone isn't enough. An extra step like 'confirm login' makes account takeover much harder.",
      },
      {
        id: 4,
        text: "İşten ayrılan çalışanların şirket sistemlerine ve e-postaya erişimi aynı gün kapatılıyor mu?",
        enText: "Are departed employees' access to company systems and email closed on the same day they leave?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Ayrılan çalışanın hesabı açık kalırsa istemeden veya bilerek şirket verilerine erişebilir.",
        enHelpText: "If a former employee's account remains open, they can intentionally or unintentionally access company data.",
      },
    ]
  },
  {
    id: "C",
    title: "E-posta ve Sosyal Mühendislik",
    enTitle: "Email & Social Engineering",
    questions: [
      {
        id: 5,
        text: "IBAN değişikliği veya acil para transferi taleplerinde e-postaya ek olarak telefon ile doğrulama yapılıyor mu?",
        enText: "For IBAN changes or urgent money transfer requests, is phone verification done in addition to email?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Saldırganlar yönetici gibi görünerek \"acil havale yap\" e-postası gönderiyor. Telefon ile teyit bu saldırıyı engeller.",
        enHelpText: "Attackers send 'urgent wire transfer' emails pretending to be managers. Phone confirmation stops this attack.",
      },
      {
        id: 6,
        text: "Şirket e-posta adresinizin taklit edilerek sahte mail gönderilmesini engelleyen teknik önlem alındı mı?",
        enText: "Have technical measures been taken to prevent your company email address from being spoofed to send fake emails?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Teknik önlem alınmadan saldırganlar sizin adınıza e-posta gönderebilir. Bu konuda IT destek aldınız mı?",
        enHelpText: "Without technical measures, attackers can send emails in your name. Have you received IT support for this?",
      },
    ]
  },
  {
    id: "D",
    title: "Cihaz ve Uç Nokta Güvenliği",
    enTitle: "Device & Endpoint Security",
    questions: [
      {
        id: 7,
        text: "Şirket bilgisayarlarında güncel zararlı yazılım koruma (antivirüs/güvenlik) çözümü aktif mi?",
        enText: "Is an up-to-date malware protection (antivirus/security) solution active on company computers?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Sadece Windows Defender yeterli değildir. Kurumsal bir güvenlik çözümü merkezi olarak yönetilmeli.",
        enHelpText: "Windows Defender alone is not sufficient. A corporate security solution should be centrally managed.",
      },
      {
        id: 8,
        text: "Bilgisayarlar ve iş yazılımları (Windows, Office, muhasebe programı vb.) düzenli olarak güncelleniyor mu?",
        enText: "Are computers and business software (Windows, Office, accounting software, etc.) updated regularly?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Güncellenmemiş yazılımlar saldırganların en çok kullandığı giriş kapısı. Otomatik güncelleme açık mı?",
        enHelpText: "Unpatched software is the most common entry point for attackers. Is automatic update enabled?",
      },
    ]
  },
  {
    id: "E",
    title: "Ağ Güvenliği",
    enTitle: "Network Security",
    questions: [
      {
        id: 9,
        text: "Şirketin internet bağlantısını koruyan bir güvenlik duvarı (firewall) aktif ve yapılandırılmış mı?",
        enText: "Is a firewall protecting the company's internet connection active and configured?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Modem/router içindeki basit güvenlik duvarı yeterli değildir. Kurumsal bir firewall cihazı veya yazılımı var mı?",
        enHelpText: "The basic firewall in your modem/router is not enough. Is there a dedicated corporate firewall device or software?",
      },
      {
        id: 10,
        text: "Müşteri veya ziyaretçilere sunulan Wi-Fi ağı, şirketin iç ağından tamamen ayrı mı?",
        enText: "Is the Wi-Fi network offered to customers or visitors completely separate from the company's internal network?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Aynı Wi-Fi'ye bağlanan bir ziyaretçi, iç sistemlerinize erişebilir. Misafir ağı ayrı mı?",
        enHelpText: "A visitor connected to the same Wi-Fi can access your internal systems. Is the guest network separate?",
      },
    ]
  },
  {
    id: "F",
    title: "Veri Koruma ve Yedekleme",
    enTitle: "Data Protection & Backup",
    questions: [
      {
        id: 11,
        text: "Kritik verileriniz düzenli ve tercihen otomatik olarak yedekleniyor mu?",
        enText: "Are critical data backed up regularly and preferably automatically?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Fidye yazılımı saldırısında yedek yoksa tüm verilerinizi kaybedebilirsiniz. Günlük otomatik yedek var mı?",
        enHelpText: "In a ransomware attack without a backup, you could lose all your data. Is there a daily automatic backup?",
      },
      {
        id: 12,
        text: "Alınan yedeklerin gerçekten çalıştığı son 12 ay içinde test edildi mi?",
        enText: "Has it been tested within the last 12 months that the backups actually work?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Yedek almak yetmez; geri yüklenip yüklenmediği de test edilmeli. Son ne zaman denendi?",
        enHelpText: "Taking a backup isn't enough; it must also be tested for successful restoration. When was the last test?",
      },
    ]
  },
  {
    id: "G",
    title: "Yazılım ve Dijital Araçlar",
    enTitle: "Software & Digital Tools",
    questions: [
      {
        id: 13,
        text: "Muhasebe, ERP veya stok yazılımına her çalışan kendi kullanıcı adı ve şifresiyle giriyor mu?",
        enText: "Does each employee log into accounting, ERP, or inventory software with their own username and password?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Ortak kullanılan tek şifre, kimin ne yaptığını izlemeyi imkânsız kılar ve güvenlik riskini artırır.",
        enHelpText: "A shared single password makes it impossible to track who did what and increases security risk.",
      },
      {
        id: 14,
        text: "Çalışanların ChatGPT gibi yapay zeka araçlarına şirket verisi, müşteri bilgisi veya sözleşme yüklemesini önleyen kural var mı?",
        enText: "Is there a policy preventing employees from uploading company data, customer information, or contracts to AI tools like ChatGPT?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Yapay zeka araçlarına yüklenen veriler üçüncü taraf sunucularda saklanabilir. KVKK açısından risk taşır.",
        enHelpText: "Data uploaded to AI tools can be stored on third-party servers. This carries risk under KVKK.",
      },
    ]
  },
  {
    id: "H",
    title: "Fiziksel Güvenlik",
    enTitle: "Physical Security",
    questions: [
      {
        id: 15,
        text: "Sunucu, ağ cihazı veya kritik sistemlerin bulunduğu alanlara yetkisiz kişilerin girmesi engelleniyor mu?",
        enText: "Is access to areas containing servers, network equipment, or critical systems restricted from unauthorized persons?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Sunucu odası kilitli mi? Kimler girebilir? Fiziksel erişim, dijital saldırı kadar ciddi bir risktir.",
        enHelpText: "Is the server room locked? Who can enter? Physical access is as serious a risk as digital attacks.",
      },
      {
        id: 16,
        text: "Müşteri bilgisi veya finansal veri içeren belgeler güvenli şekilde imha ediliyor mu (kağıt parçalama vb.)?",
        enText: "Are documents containing customer information or financial data securely destroyed (paper shredding, etc.)?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Çöpe atılan belgeler bilgi hırsızlığına yol açabilir. Kağıt imha makinesi kullanılıyor mu?",
        enHelpText: "Documents thrown in the trash can lead to information theft. Is a paper shredder being used?",
      },
    ]
  },
  {
    id: "I",
    title: "Tedarik Zinciri ve Dijital Varlıklar",
    enTitle: "Supply Chain & Digital Assets",
    questions: [
      {
        id: 17,
        text: "Şirketin sosyal medya hesaplarına (Instagram, LinkedIn vb.) kimlerin erişimi var ve bu hesaplarda 2FA aktif mi?",
        enText: "Who has access to the company's social media accounts (Instagram, LinkedIn, etc.) and is 2FA active on these accounts?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Hesap ele geçirilmesi hem itibar kaybına hem müşteri dolandırıcılığına yol açar. Kaç kişi bu şifreleri biliyor?",
        enHelpText: "Account takeover can lead to both reputational damage and customer fraud. How many people know these passwords?",
      },
      {
        id: 18,
        text: "Web sitesinin alan adı (domain) yenileme tarihi takip ediliyor ve bu konuda sorumlu kişi belirlenmiş mi?",
        enText: "Is the company website's domain renewal date tracked and has a responsible person been designated for this?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Domain yenilenmezse web siteniz ve e-postanız tamamen durur. Son yenileme ne zaman yapıldı?",
        enHelpText: "If the domain isn't renewed, your website and email will completely stop working. When was the last renewal?",
      },
    ]
  },
  {
    id: "J",
    title: "Olay Müdahalesi ve İş Sürekliliği",
    enTitle: "Incident Response & Business Continuity",
    questions: [
      {
        id: 19,
        text: "Şirkete siber saldırı yaşanırsa ilk 1 saatte kimin ne yapacağı önceden belirlenmiş mi?",
        enText: "If the company suffers a cyberattack, has it been predetermined who does what in the first hour?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Panik anında plan yoksa değerli zaman kaybedilir. \"Kim aranır, ne kapatılır, kim bilgilendirilir?\" yazılı mı?",
        enHelpText: "Without a plan in a panic, valuable time is lost. Is 'who to call, what to shut down, who to notify' documented?",
      },
      {
        id: 20,
        text: "KVKK kapsamında müşteri verisi sızdığında 72 saat içinde bildirim yapma yükümlülüğünüz için hazırlık yapıldı mı?",
        enText: "Under KVKK, has preparation been made for the obligation to notify within 72 hours if customer data is breached?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Kanuni zorunluluk: veri ihlalini öğrendiğinizden itibaren 72 saat içinde KVK Kurulu'na bildirim yapılmalı.",
        enHelpText: "Legal requirement: data breaches must be reported to the KVKK Authority within 72 hours of discovery.",
      },
    ]
  },
];

export const FULL_ASSESSMENT_SECTIONS = [
  {
    id: "A",
    title: "Yönetişim ve Risk Yönetimi",
    enTitle: "Governance & Risk Management",
    questions: [
      {
        id: 1,
        text: "Şirketinizde siber güvenlikten sorumlu atanmış bir kişi veya ekip var mı?",
        enText: "Does your company have a designated person or team responsible for cybersecurity?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Bu kişinin teknik uzman olması şart değil. Siber güvenlik konusunda kararları kim alıyor, sorunları kim çözüyor?",
        enHelpText: "This person doesn't need to be a technical expert. Who makes cybersecurity decisions and resolves issues?",
      },
      {
        id: 2,
        text: "Yıllık siber güvenlik bütçesi planlanıyor mu?",
        enText: "Is an annual cybersecurity budget planned?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Küçük bir bütçe bile olsa, güvenlik için ayrılan kaynağın belirlenmesi önemli bir olgunluk göstergesi.",
        enHelpText: "Even a small budget, having a defined resource for security is an important maturity indicator.",
      },
      {
        id: 3,
        text: "Çalışanların şirket bilgisayarları, hesapları ve verilerini nasıl kullanacağına dair yazılı kurallar mevcut mu?",
        enText: "Are there written rules on how employees should use company computers, accounts, and data?",
        isCritical: false,
        weight: 1 as const,
        helpText: "\"Kabul Edilebilir Kullanım Politikası\" olarak da bilinir. İmzalatılmış bir belge var mı?",
        enHelpText: "Also known as an 'Acceptable Use Policy'. Is there a signed document?",
      },
      {
        id: 4,
        text: "Şirkette kullanılan tüm sistemler, yazılımlar ve hassas verilerin nerede tutulduğuna dair güncel bir liste var mı?",
        enText: "Is there an up-to-date inventory of all systems, software, and where sensitive data is stored?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Hangi verinin hangi sistemde olduğunu bilmeden onu koruyamazsınız.",
        enHelpText: "You can't protect data you don't know where it is.",
      },
      {
        id: 5,
        text: "Üst yönetim veya ortaklar, şirketin siber güvenlik risklerini düzenli olarak gündeme alıyor mu?",
        enText: "Do senior management or partners regularly review the company's cybersecurity risks?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Yılda en az bir kez bile olsa, güvenlik durumunun üst yönetime raporlanması kritik.",
        enHelpText: "Even once a year, reporting the security status to senior management is critical.",
      },
      {
        id: 6,
        text: "Yeni işe giren çalışanlara işe başlarken siber güvenlik kuralları ve sorumlulukları anlatılıyor mu?",
        enText: "Are cybersecurity rules and responsibilities explained to new employees at onboarding?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Oryantasyon eğitimi, insan kaynaklı hataları ve ihmalleri önemli ölçüde azaltır.",
        enHelpText: "Onboarding training significantly reduces human error and negligence.",
      },
    ]
  },
  {
    id: "B",
    title: "Kimlik ve Erişim Yönetimi",
    enTitle: "Identity & Access Management",
    questions: [
      {
        id: 7,
        text: "Tüm çalışanlar için güçlü ve farklı şifreler kullanmaları zorunlu mu?",
        enText: "Are all employees required to use strong and unique passwords?",
        isCritical: false,
        weight: 1 as const,
        helpText: "En az 12 karakter, büyük/küçük harf, rakam ve sembol içeren şifre. Aynı şifrenin birden fazla yerde kullanımı yasaklı mı?",
        enHelpText: "At least 12 characters including upper/lowercase letters, numbers, and symbols. Is reusing the same password across multiple sites prohibited?",
      },
      {
        id: 8,
        text: "Çalışanlar iş uygulamaları ve e-postaya SMS kodu veya uygulama onayı (2FA) ile giriş yapıyor mu?",
        enText: "Do employees log into work applications and email using an SMS code or app confirmation (2FA)?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Bu tek önlem bile hesap ele geçirme saldırılarının büyük çoğunluğunu engeller.",
        enHelpText: "This single measure alone prevents the vast majority of account takeover attacks.",
      },
      {
        id: 9,
        text: "Şirkete dışarıdan bağlanan çalışanlar ve IT yetkilileri ek doğrulama (VPN + 2FA) kullanıyor mu?",
        enText: "Do employees and IT staff connecting remotely use additional verification (VPN + 2FA)?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Uzak erişim, saldırganların en çok hedeflediği giriş noktası. Ekstra koruma şart.",
        enHelpText: "Remote access is the most targeted entry point by attackers. Extra protection is essential.",
      },
      {
        id: 10,
        text: "İşten ayrılan çalışanların tüm sistem, uygulama ve e-posta erişimleri ayrılış günü kapatılıyor mu?",
        enText: "Are all system, application, and email accesses of departed employees closed on the day they leave?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Ayrılan çalışanın hesabı açık kalması en yaygın güvenlik açıklarından. Prosedür yazılı mı?",
        enHelpText: "Leaving a departed employee's account open is one of the most common security vulnerabilities. Is the procedure documented?",
      },
      {
        id: 11,
        text: "Çalışanlar yalnızca kendi işleri için ihtiyaç duydukları sistemlere ve dosyalara erişebiliyor mu?",
        enText: "Can employees only access the systems and files they need for their own work?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Muhasebeci neden üretim verilerine erişebilsin? Her çalışan sadece ihtiyacı kadar yetkiye sahip olmalı.",
        enHelpText: "Why should an accountant have access to production data? Each employee should only have the permissions they need.",
      },
      {
        id: 12,
        text: "Sistem yöneticisi veya IT yetkilisi hesapları düzenli olarak gözden geçiriliyor ve denetleniyor mu?",
        enText: "Are system administrator or IT staff accounts regularly reviewed and audited?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Yüksek yetkili hesaplar en çok hedef alınanlardır. Bunların listesi ve kullanım kaydı tutuluyor mu?",
        enHelpText: "High-privilege accounts are the most targeted. Is a list and usage log maintained for these?",
      },
    ]
  },
  {
    id: "C",
    title: "E-posta ve Sosyal Mühendislik",
    enTitle: "Email & Social Engineering",
    questions: [
      {
        id: 13,
        text: "Çalışanlara yılda en az bir kez sahte e-posta (phishing) ve dolandırıcılık farkındalık eğitimi veriliyor mu?",
        enText: "Are employees given phishing and fraud awareness training at least once a year?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Saldırıların büyük çoğunluğu çalışanları kandırarak başlar. Farkındalık eğitimi en etkili savunma araçlarından.",
        enHelpText: "The majority of attacks begin by deceiving employees. Awareness training is one of the most effective defenses.",
      },
      {
        id: 14,
        text: "Şüpheli e-postaları bildirmek için çalışanların başvurabileceği net bir kişi veya kanal tanımlanmış mı?",
        enText: "Is there a clear person or channel defined for employees to report suspicious emails?",
        isCritical: false,
        weight: 1 as const,
        helpText: "\"Şüpheli bir şey gördüm, kime söyleyeyim?\" sorusunun cevabı her çalışan tarafından biliniyor mu?",
        enHelpText: "Does every employee know the answer to 'I saw something suspicious, who do I tell?'",
      },
      {
        id: 15,
        text: "Gelen e-postalarda zararlı ek ve bağlantıları filtreleyen bir güvenlik sistemi aktif mi?",
        enText: "Is an email security system active that filters malicious attachments and links in incoming emails?",
        isCritical: false,
        weight: 2 as const,
        helpText: "E-posta güvenlik filtresi, zararlı e-postaların gelen kutusuna ulaşmadan engellenmesini sağlar.",
        enHelpText: "An email security filter prevents malicious emails from reaching the inbox.",
      },
      {
        id: 16,
        text: "Şirket e-posta adresinin taklit edilmesini engelleyen teknik ayarlar (SPF, DKIM, DMARC) yapılandırılmış mı?",
        enText: "Have technical settings (SPF, DKIM, DMARC) been configured to prevent your company email address from being spoofed?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Bu ayarlar olmadan, saldırganlar sizin adınıza e-posta göndererek müşterilerinizi ve çalışanlarınızı kandırabilir.",
        enHelpText: "Without these settings, attackers can send emails in your name to deceive your customers and employees.",
      },
      {
        id: 17,
        text: "IBAN değişikliği veya acil para transferi gibi taleplerde e-postaya ek olarak telefon ile doğrulama yapılıyor mu?",
        enText: "For requests like IBAN changes or urgent money transfers, is phone verification done in addition to email?",
        isCritical: true,
        weight: 3 as const,
        helpText: "\"CEO Dolandırıcılığı\": Saldırgan yönetici kılığına girerek \"acil havale yap\" e-postası gönderir. Telefon teyidi bunu engeller.",
        enHelpText: "'CEO Fraud': The attacker disguises as a manager and sends an 'urgent wire transfer' email. Phone confirmation stops this.",
      },
      {
        id: 18,
        text: "Şirket içi iletişim ve müşteri yazışmaları için kullanılan WhatsApp gruplarına dair güvenlik kuralı var mı?",
        enText: "Is there a security policy regarding WhatsApp groups used for internal communication and customer correspondence?",
        isCritical: false,
        weight: 1 as const,
        helpText: "WhatsApp gruplarında paylaşılan sözleşme, fatura veya müşteri bilgisi KVKK riski doğurabilir.",
        enHelpText: "Contracts, invoices, or customer information shared in WhatsApp groups can create KVKK risk.",
      },
    ]
  },
  {
    id: "D",
    title: "Cihaz ve Uç Nokta Güvenliği",
    enTitle: "Device & Endpoint Security",
    questions: [
      {
        id: 19,
        text: "Şirkette kullanılan tüm bilgisayarların güncel bir envanteri tutuluyor mu?",
        enText: "Is an up-to-date inventory of all computers used in the company maintained?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Hangi bilgisayar var, kimin kullandığı, hangi yazılım yüklü? Bu liste olmadan güvenliği yönetmek mümkün değil.",
        enHelpText: "Which computers exist, who uses them, what software is installed? Without this list, managing security is impossible.",
      },
      {
        id: 20,
        text: "Çalışan bilgisayarlarında merkezi olarak yönetilen zararlı yazılım koruma çözümü (EDR/antivirüs) aktif mi?",
        enText: "Is a centrally managed malware protection solution (EDR/antivirus) active on employee computers?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Her bilgisayarda aynı koruma yazılımı, merkezi izleme ile yönetilmeli. Sadece Windows Defender yeterli değil.",
        enHelpText: "The same protection software on every computer, managed with central monitoring. Windows Defender alone is not enough.",
      },
      {
        id: 21,
        text: "İşletim sistemi ve iş uygulamaları otomatik olarak güncelleniyor mu?",
        enText: "Are operating systems and business applications updated automatically?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Güncelleme gecikmesi, bilinen açıkların istismarını kolaylaştırır. Otomatik güncelleme açık mı?",
        enHelpText: "Update delays make exploiting known vulnerabilities easier. Is automatic update enabled?",
      },
      {
        id: 22,
        text: "Dizüstü bilgisayar ve mobil cihazlarda ekran kilidi ve disk şifrelemesi aktif mi?",
        enText: "Are screen lock and disk encryption active on laptops and mobile devices?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Cihaz çalınırsa veya kaybolursa şifrelenmiş disk, verilerin ele geçirilmesini engeller.",
        enHelpText: "If a device is stolen or lost, an encrypted disk prevents data from being accessed.",
      },
      {
        id: 23,
        text: "Çalışanların kişisel cihazlarıyla (kendi telefon/bilgisayar) şirket sistemlerine bağlanmasına dair yazılı kural var mı?",
        enText: "Is there a written policy on employees connecting to company systems with their personal devices (own phone/computer)?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Kişisel cihazlar şirket güvenlik standartlarını karşılamayabilir. Bu konuda politika belirlenmiş mi?",
        enHelpText: "Personal devices may not meet company security standards. Has a policy been established on this?",
      },
      {
        id: 24,
        text: "USB ve taşınabilir bellek kullanımı şirket bilgisayarlarında denetleniyor veya kısıtlanıyor mu?",
        enText: "Is the use of USB drives and portable storage controlled or restricted on company computers?",
        isCritical: false,
        weight: 1 as const,
        helpText: "USB yoluyla veri sızdırma ve zararlı yazılım bulaştırma hâlâ yaygın bir saldırı yöntemi.",
        enHelpText: "Data exfiltration and malware infection via USB are still common attack methods.",
      },
    ]
  },
  {
    id: "E",
    title: "Ağ Güvenliği",
    enTitle: "Network Security",
    questions: [
      {
        id: 25,
        text: "Şirketin internet bağlantısını koruyan kurumsal güvenlik duvarı (firewall) aktif ve yapılandırılmış mı?",
        enText: "Is a corporate firewall protecting the company's internet connection active and configured?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Modem içindeki temel koruma kurumsal ağ için yeterli değil. Ayrı bir firewall cihazı veya yazılımı var mı?",
        enHelpText: "The basic protection inside the modem is not enough for a corporate network. Is there a separate firewall device or software?",
      },
      {
        id: 26,
        text: "Misafir veya müşteri Wi-Fi ağı şirketin iç ağından tamamen ayrılmış mı?",
        enText: "Is the guest or customer Wi-Fi network completely separated from the company's internal network?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Aynı ağa bağlanan bir ziyaretçi, iç sistemlere erişebilir. Ayrı bir misafir SSID var mı?",
        enHelpText: "A visitor connected to the same network can access internal systems. Is there a separate guest SSID?",
      },
      {
        id: 27,
        text: "Ağ trafiği izleniyor ve olağandışı bağlantılar için uyarı sistemi kurulu mu?",
        enText: "Is network traffic monitored and is an alert system set up for unusual connections?",
        isCritical: false,
        weight: 2 as const,
        helpText: "\"Gece 3'te Rusya'ya veri gidiyor\" gibi anomalileri tespit eden bir sistem var mı?",
        enHelpText: "Is there a system that detects anomalies like 'data going to Russia at 3am'?",
      },
      {
        id: 28,
        text: "Finans sistemi, müşteri veri tabanı gibi kritik sistemler ağ içinde diğerlerinden ayrılmış mı?",
        enText: "Are critical systems like finance systems and customer databases separated from others within the network?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Ağ segmentasyonu: bir bölüme sızan saldırgan otomatik olarak diğer bölümlere geçememeli.",
        enHelpText: "Network segmentation: an attacker who breaches one segment should not automatically access others.",
      },
      {
        id: 29,
        text: "Kullanılmayan ağ portları ve servisler kapalı mı?",
        enText: "Are unused network ports and services closed?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Açık her port potansiyel giriş kapısıdır. Düzenli port taraması yapılıyor mu?",
        enHelpText: "Every open port is a potential entry point. Is regular port scanning performed?",
      },
      {
        id: 30,
        text: "Şirket dışından yönetim amaçlı sisteme bağlanmak (uzak masaüstü vb.) VPN üzerinden yapılıyor mu?",
        enText: "Is remote management access to the company system (remote desktop, etc.) done through a VPN?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Doğrudan açık RDP bağlantısı, fidye yazılımının en yaygın giriş noktası. VPN zorunlu mu?",
        enHelpText: "A directly open RDP connection is the most common ransomware entry point. Is VPN mandatory?",
      },
    ]
  },
  {
    id: "F",
    title: "Veri Koruma ve Yedekleme",
    enTitle: "Data Protection & Backup",
    questions: [
      {
        id: 31,
        text: "Kritik veriler düzenli ve tercihen otomatik olarak yedekleniyor mu?",
        enText: "Are critical data backed up regularly and preferably automatically?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Fidye yazılımı saldırısında yedek olmadan tüm verilerinizi kaybedebilirsiniz. Günlük otomatik yedek var mı?",
        enHelpText: "In a ransomware attack without a backup, you could lose all your data. Is there a daily automatic backup?",
      },
      {
        id: 32,
        text: "Yedekler, ana sistemden fiziksel veya ağ olarak tamamen ayrı bir ortamda tutuluyor mu?",
        enText: "Are backups kept in a completely separate environment (physically or network-isolated) from the main system?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Fidye yazılımı bağlı tüm diskleri şifreler. Yedek ayrı bir yerde (farklı lokasyon veya çevrimdışı disk) durmalı.",
        enHelpText: "Ransomware encrypts all connected disks. Backups must be kept separately (different location or offline disk).",
      },
      {
        id: 33,
        text: "Yedeklerin başarıyla geri yüklenip yüklenmediği son 12 ay içinde test edildi mi?",
        enText: "Has it been tested within the last 12 months whether backups can be successfully restored?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Alınan yedeğin gerçekten çalışıp çalışmadığı test edilmeden güvenilir sayılamaz.",
        enHelpText: "A backup cannot be considered reliable without testing whether it actually works.",
      },
      {
        id: 34,
        text: "Müşteri veya çalışanlara ait hassas veriler dışarıya gönderilirken şifreleniyor mu?",
        enText: "Is sensitive data belonging to customers or employees encrypted when sent externally?",
        isCritical: false,
        weight: 1 as const,
        helpText: "E-posta eki, dosya transferi veya bulut paylaşımında hassas veri şifrelenmeli.",
        enHelpText: "Sensitive data must be encrypted in email attachments, file transfers, or cloud sharing.",
      },
      {
        id: 35,
        text: "Sunucularda veya bulutta depolanan hassas veriler şifreli mi?",
        enText: "Is sensitive data stored on servers or in the cloud encrypted?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Disk şifreleme: birisi fiziksel olarak erişse bile veri okunamaz olmalı.",
        enHelpText: "Disk encryption: even if someone gains physical access, the data should be unreadable.",
      },
      {
        id: 36,
        text: "KVKK kapsamındaki kişisel veriler (müşteri, çalışan bilgisi) için gerekli teknik ve idari tedbirler alındı mı?",
        enText: "Have the necessary technical and administrative measures been taken for personal data (customer, employee information) under KVKK?",
        isCritical: true,
        weight: 3 as const,
        helpText: "KVKK Madde 12 teknik önlem zorunluluğu. Yeterli önlem alınmadan yaşanan ihlallerde ceza artırılıyor.",
        enHelpText: "KVKK Article 12 technical measure obligation. Penalties are increased for breaches without adequate measures.",
      },
    ]
  },
  {
    id: "G",
    title: "Yazılım, Dijital Araçlar ve Hesap Güvenliği",
    enTitle: "Software, Digital Tools & Account Security",
    questions: [
      {
        id: 37,
        text: "Muhasebe, ERP veya stok yazılımına her çalışan kendi kullanıcı adı ve şifresiyle giriyor mu?",
        enText: "Does each employee log into accounting, ERP, or inventory software with their own username and password?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Ortak kullanılan tek şifre, kimin ne yaptığını izlemeyi imkânsız kılar ve yetkisiz erişim riskini artırır.",
        enHelpText: "A shared single password makes it impossible to track who did what and increases unauthorized access risk.",
      },
      {
        id: 38,
        text: "Kullanılan üçüncü taraf yazılım ve sistemlerin güvenlik güncellemeleri düzenli takip ediliyor mu?",
        enText: "Are security updates for third-party software and systems regularly tracked?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Muhasebe yazılımı, ERP, CRM — bunların güncel ve destek kapsamında olması kritik.",
        enHelpText: "Accounting software, ERP, CRM — it's critical that these are up to date and within support coverage.",
      },
      {
        id: 39,
        text: "Çalışanların ChatGPT gibi yapay zeka araçlarına şirket verisi, müşteri bilgisi veya gizli belge yüklemesini önleyen kural veya farkındalık çalışması yapıldı mı?",
        enText: "Has a policy or awareness effort been made to prevent employees from uploading company data, customer information, or confidential documents to AI tools like ChatGPT?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Bu araçlara yüklenen veriler üçüncü taraf sunucularda işlenir. KVKK ve gizlilik açısından ciddi risk taşır.",
        enHelpText: "Data uploaded to these tools is processed on third-party servers. This carries serious risk under KVKK and confidentiality.",
      },
      {
        id: 40,
        text: "Şirket web sitesi veya e-ticaret platformu düzenli güvenlik kontrolünden geçiyor mu?",
        enText: "Does the company website or e-commerce platform undergo regular security checks?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Web siteniz ele geçirilirse müşterileriniz dolandırılabilir, KVKK yükümlülüğünüz doğar.",
        enHelpText: "If your website is compromised, your customers can be defrauded and your KVKK obligations arise.",
      },
      {
        id: 41,
        text: "Bulut depolama (Google Drive, OneDrive, Dropbox) paylaşım izinleri düzenli gözden geçiriliyor mu?",
        enText: "Are cloud storage (Google Drive, OneDrive, Dropbox) sharing permissions regularly reviewed?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Eski çalışanlara veya harici kişilere verilmiş dosya izinleri kaldırıldı mı?",
        enHelpText: "Have file permissions granted to former employees or external parties been removed?",
      },
      {
        id: 42,
        text: "Şirket sosyal medya hesaplarına (Instagram, LinkedIn, Twitter/X vb.) kimlerin erişimi var ve bu hesaplarda 2FA aktif mi?",
        enText: "Who has access to company social media accounts (Instagram, LinkedIn, Twitter/X, etc.) and is 2FA active on these accounts?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Sosyal medya hesabı ele geçirilmesi, müşteri dolandırıcılığına ve itibar kaybına yol açar.",
        enHelpText: "Social media account takeover leads to customer fraud and reputational damage.",
      },
    ]
  },
  {
    id: "H",
    title: "Fiziksel Güvenlik",
    enTitle: "Physical Security",
    questions: [
      {
        id: 43,
        text: "Sunucu, ağ cihazı veya kritik sistemlerin bulunduğu alanlara yetkisiz kişilerin girmesi engelleniyor mu?",
        enText: "Is access to areas containing servers, network equipment, or critical systems restricted from unauthorized persons?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Kilitsiz sunucu odası = doğrudan veri erişimi. Fiziksel güvenlik, dijital kadar önemli.",
        enHelpText: "Unlocked server room = direct data access. Physical security is as important as digital.",
      },
      {
        id: 44,
        text: "Ofise gelen ziyaretçiler kayıt altına alınıyor ve iç alanlarda yalnız bırakılmıyor mu?",
        enText: "Are visitors to the office logged and not left alone in internal areas?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Ziyaretçi güvenlik politikası var mı? Misafir defteri veya elektronik kayıt tutuluyor mu?",
        enHelpText: "Is there a visitor security policy? Is a visitor log or electronic record maintained?",
      },
      {
        id: 45,
        text: "Çalışanların masayı terk ederken bilgisayar ekranlarını kilitlemesi zorunlu mu?",
        enText: "Are employees required to lock their computer screens when leaving their desk?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Dakikalık bir ihmal, yetkisiz kişinin ekranı görmesine veya sisteme erişmesine yol açabilir.",
        enHelpText: "A momentary lapse can allow an unauthorized person to see the screen or access the system.",
      },
      {
        id: 46,
        text: "Müşteri bilgisi veya finansal veri içeren hassas belgeler güvenli şekilde imha ediliyor mu?",
        enText: "Are sensitive documents containing customer information or financial data securely destroyed?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Kağıt imha makinesi kullanılıyor mu? Çöpe atılan belgeler ciddi bilgi sızıntısı riski taşır.",
        enHelpText: "Is a paper shredder used? Documents thrown in the trash carry serious information leak risk.",
      },
      {
        id: 47,
        text: "Ofis dışında çalışılırken (ev, kafe, havalimanı) uyulması gereken cihaz güvenlik kuralları belirlenmiş mi?",
        enText: "Have device security rules been established for working outside the office (home, café, airport)?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Halka açık Wi-Fi'de şifrelenmemiş bağlantı, VPN yoksa veri ele geçirme riski yaratır.",
        enHelpText: "An unencrypted connection on public Wi-Fi creates data interception risk without a VPN.",
      },
      {
        id: 48,
        text: "Şirket cihazının kaybolması veya çalınması durumunda ne yapılacağı önceden belirlenmiş mi?",
        enText: "Has it been predetermined what to do if a company device is lost or stolen?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Uzaktan silme, şifre değiştirme, bildirme prosedürü — bunlar tanımlı mı?",
        enHelpText: "Remote wipe, password change, notification procedure — are these defined?",
      },
    ]
  },
  {
    id: "I",
    title: "Tedarik Zinciri ve Üçüncü Taraf Yönetimi",
    enTitle: "Supply Chain & Third-Party Management",
    questions: [
      {
        id: 49,
        text: "Kritik hizmet sağlayıcıların (muhasebe yazılımı, bulut, ödeme sistemi) güvenlik uygulamaları değerlendiriliyor mu?",
        enText: "Are the security practices of critical service providers (accounting software, cloud, payment systems) evaluated?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Tedarikçiniz hacklenirse siz de etkilenebilirsiniz. Tedarikçi güvenliği kontrol ediliyor mu?",
        enHelpText: "If your supplier is hacked, you can be affected too. Is supplier security being checked?",
      },
      {
        id: 50,
        text: "Dışarıdan çalışan muhasebeci, mali müşavir veya IT firmasının sistem erişimi sınırlı ve kayıt altında mı?",
        enText: "Is the system access of external accountants, financial advisors, or IT firms limited and logged?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Dış paydaşlar en az ayrıcalık prensibiyle yönetilmeli ve erişimleri işleri bittikten sonra kaldırılmalı.",
        enHelpText: "External stakeholders should be managed with the least privilege principle and access removed after their work is done.",
      },
      {
        id: 51,
        text: "Tedarikçi ve iş ortağı sözleşmelerinde veri gizliliği ve güvenlik maddeleri yer alıyor mu?",
        enText: "Do supplier and business partner contracts include data privacy and security clauses?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Müşteri verisi paylaşılan her iş ortağıyla KVKK uyumlu veri işleme sözleşmesi (DPA) imzalanmalı.",
        enHelpText: "A KVKK-compliant data processing agreement (DPA) must be signed with every business partner with whom customer data is shared.",
      },
      {
        id: 52,
        text: "Bulut hizmet sağlayıcılarının (hosting, e-posta, depolama) güvenlik sertifikasyonları kontrol ediliyor mu?",
        enText: "Are the security certifications of cloud service providers (hosting, email, storage) checked?",
        isCritical: false,
        weight: 1 as const,
        helpText: "ISO 27001, SOC 2 gibi sertifikalar, sağlayıcının minimum güvenlik standartlarını karşıladığını gösterir.",
        enHelpText: "Certifications like ISO 27001 and SOC 2 show that the provider meets minimum security standards.",
      },
      {
        id: 53,
        text: "Web sitesinin alan adı (domain) yenileme tarihi takip ediliyor ve sorumlu kişi belirlenmiş mi?",
        enText: "Is the website's domain renewal date tracked and has a responsible person been designated?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Domain süresi dolarsa web siteniz ve tüm e-postalarınız anında çalışmayı durdurur.",
        enHelpText: "If the domain expires, your website and all emails will immediately stop working.",
      },
      {
        id: 54,
        text: "Üçüncü taraf erişimleri sadece ihtiyaç duydukları sistemlerle sınırlı tutuluyor mu?",
        enText: "Is third-party access limited only to the systems they need?",
        isCritical: false,
        weight: 2 as const,
        helpText: "IT firmanız neden muhasebe verilerinize erişebilsin? Her dış erişim minimum yetki ile sınırlı olmalı.",
        enHelpText: "Why should your IT firm have access to your accounting data? Every external access should be limited to minimum permissions.",
      },
    ]
  },
  {
    id: "J",
    title: "Olay Müdahalesi ve İş Sürekliliği",
    enTitle: "Incident Response & Business Continuity",
    questions: [
      {
        id: 55,
        text: "Siber saldırı veya veri ihlali yaşanırsa ilk 1 saatte kimin ne yapacağı yazılı olarak belirlenmiş mi?",
        enText: "If a cyberattack or data breach occurs, has it been documented in writing who does what in the first hour?",
        isCritical: true,
        weight: 3 as const,
        helpText: "Panik anında plan yoksa kritik saatler boşa gider. Acil müdahale planı hazır mı?",
        enHelpText: "Without a plan in a panic, critical hours are wasted. Is an emergency response plan ready?",
      },
      {
        id: 56,
        text: "Olay müdahale planı son 12 ay içinde tatbikatla test edildi mi?",
        enText: "Has the incident response plan been tested with a drill within the last 12 months?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Yazılı plan yetmez; pratikte de çalışıp çalışmadığı test edilmeli.",
        enHelpText: "A written plan isn't enough; it must also be tested to see if it works in practice.",
      },
      {
        id: 57,
        text: "Siber saldırı sonrası müşterilere, iş ortaklarına ve yasal makamlara bildirim yapma süreci tanımlı mı?",
        enText: "Is the notification process to customers, business partners, and legal authorities after a cyberattack defined?",
        isCritical: false,
        weight: 1 as const,
        helpText: "\"Kiminle nasıl iletişim kurarız?\" sorusunun cevabı kriz anında değil öncesinde hazırlanmalı.",
        enHelpText: "The answer to 'Who do we contact and how?' should be prepared before a crisis, not during.",
      },
      {
        id: 58,
        text: "KVKK kapsamında veri ihlali yaşanırsa 72 saat içinde KVK Kurulu'na bildirim yapma yükümlülüğü için hazırlık yapıldı mı?",
        enText: "Has preparation been made for the obligation to notify the KVKK Authority within 72 hours if a data breach occurs?",
        isCritical: false,
        weight: 2 as const,
        helpText: "Kanuni zorunluluk. 72 saati geçirmek ek idari para cezasına yol açar.",
        enHelpText: "Legal requirement. Exceeding 72 hours leads to additional administrative fines.",
      },
      {
        id: 59,
        text: "Uzun süreli sistem kesintisinde işin nasıl devam edeceğine dair iş sürekliliği planı hazırlanmış mı?",
        enText: "Has a business continuity plan been prepared for how operations will continue during a prolonged system outage?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Sunucu 3 gün çalışmazsa ne olur? Kritik işlemler manuel yürütülebilir mi?",
        enHelpText: "What happens if the server is down for 3 days? Can critical operations be performed manually?",
      },
      {
        id: 60,
        text: "Siber sigorta poliçesi değerlendirildi veya satın alındı mı?",
        enText: "Has a cyber insurance policy been evaluated or purchased?",
        isCritical: false,
        weight: 1 as const,
        helpText: "Siber sigorta; fidye ödemesi, veri kurtarma, müşteri bildirimi gibi maliyetleri karşılar.",
        enHelpText: "Cyber insurance covers costs such as ransom payment, data recovery, and customer notification.",
      },
    ]
  },
];

export const PRICING_PLANS = [
  {
    id: "mini",
    name: "Mini Değerlendirme",
    price: 0,
    priceLabel: "Ücretsiz",
    description: "İlk adım olarak şirketinizin genel siber güvenlik durumunu hızlıca öğrenin.",
    questionCount: 20,
    domainCount: 10,
    features: [
      "20 soruluk hızlı risk değerlendirmesi",
      "10 güvenlik alanı (A-J)",
      "Anlık risk skoru ve kırmızı alarm tespiti",
      "Yapay zeka destekli temel rapor",
      "Domain tarama: SPF, DMARC, DKIM, MX, SSL",
      "HIBP veri sızıntısı kontrolü",
      "Kara liste ve Shadow IT servis tespiti",
      "Sektörel kıyaslama aracı (ücretsiz)",
      "KVKK VERBİS yükümlülük kontrolü (ücretsiz)",
      "KVKK ceza simülatörü (ücretsiz)",
      "Phishing farkındalık testi (ücretsiz)",
      "Siber sigorta prim hesaplayıcı (ücretsiz)",
      "KEP ihtiyaç değerlendirmesi (ücretsiz)",
      "ERP güvenlik tarama listesi (ücretsiz)",
    ],
    notIncluded: [
      "HTTP güvenlik başlıkları analizi",
      "URLhaus & USOM zararlı alan taraması",
      "crt.sh Alt Alan Şeffaflığı (subdomain tespiti)",
      "NIST NVD CVE güvenlik açığı taraması",
      "VirusTotal domain reputation taraması",
      "AbuseIPDB IP kötüye kullanım geçmişi",
      "Shodan internet maruziyet taraması",
      "KVKK Madde 12 Teknik Tedbir Haritası",
      "NIST CSF 2.0 Uyum Seviyesi",
      "PDF rapor indirme",
      "Birebir uzman danışmanlık görüşmesi",
    ],
    cta: "Hemen Başla",
    href: "/assessment/start",
    highlight: false,
    badge: null,
  },
  {
    id: "full",
    name: "Tam Değerlendirme",
    price: 4900,
    priceLabel: "₺4.900",
    priceSuffix: "/ tek seferlik + KDV",
    description: "Derinlemesine analiz, kapsamlı tehdit istihbaratı ve birebir uzman görüşmesiyle güvenliğinizi zirveye taşıyın.",
    questionCount: 60,
    domainCount: 10,
    features: [
      "60 soruluk kapsamlı risk değerlendirmesi",
      "10 güvenlik alanı (A-J)",
      "Detaylı AI raporu",
      "Mini değerlendirmedeki tüm özellikler dahil",
      "HTTP güvenlik başlıkları analizi",
      "URLhaus & USOM zararlı alan taraması",
      "crt.sh Alt Alan Şeffaflığı (subdomain tespiti)",
      "NIST NVD CVE güvenlik açığı taraması",
      "VirusTotal domain reputation taraması",
      "AbuseIPDB IP kötüye kullanım geçmişi",
      "Shodan internet maruziyet taraması (ücretli)",
      "KVKK Madde 12 Teknik Tedbir Haritası",
      "NIST CSF 2.0 Uyum Seviyesi",
      "PDF rapor indirme",
      "30 günlük otomatik yeniden tarama bildirimi",
      "Sektörel karşılaştırma",
      "Birebir uzman danışmanlık görüşmesi (1 saat)",
    ],
    notIncluded: [],
    cta: "Satın Al",
    href: "/assessment/full/start",
    highlight: true,
    badge: "En Kapsamlı",
  },
] as const;
