import { Router, type IRouter } from "express";
import assessmentsRouter from "./assessments/index";
import geminiRouter from "./gemini/index";
import adminRouter from "./admin/index";
import customerAuthRouter from "./customer-auth/index";
import domainScanRouter from "./domain-scan/index";
import advisoriesRouter from "./advisories/index";
import kvkkRouter from "./kvkk/index";
import partnerAuthRouter from "./partner-auth/index";
import workPackagesRouter from "./work-packages/index";
import breachMonitorRouter from "./breach-monitor/index";
import toolsRouter from "./tools/index";
import tprmRouter from "./tprm/index";
import scanLeadsRouter from "./scan-leads/index";
import integrationsRouter from "./integrations/index";
import publicRouter from "./public/index";
import v1Router from "./v1/index";
import { digestRouter } from "./digest/index";
import referralRouter from "./referral/index";
import pentestLiteRouter from "./pentest-lite/index";
import healthRouter from "./health/index";
import boardReportRouter from "./board-report/index";
import aiAssessmentRouter from "./ai-assessment/index";
import aiPolicyRouter from "./ai-policy/index";
import aiMonitoringRouter from "./ai-monitoring/index";
import phishingSimRouter from "./phishing-sim/index";

const router: IRouter = Router();

router.use(publicRouter);
router.use(v1Router);
router.use(assessmentsRouter);
router.use(geminiRouter);
router.use(adminRouter);
router.use(customerAuthRouter);
router.use(domainScanRouter);
router.use(advisoriesRouter);
router.use(kvkkRouter);
router.use(partnerAuthRouter);
router.use(workPackagesRouter);
router.use(breachMonitorRouter);
router.use(toolsRouter);
router.use(tprmRouter);
router.use(scanLeadsRouter);
router.use(integrationsRouter);
router.use("/digest", digestRouter);
router.use(referralRouter);
router.use(pentestLiteRouter);
router.use(healthRouter);
router.use(boardReportRouter);
router.use(aiAssessmentRouter);
router.use(aiPolicyRouter);
router.use(aiMonitoringRouter);
router.use(phishingSimRouter);

export default router;
