import { Router, type IRouter } from "express";
import assessmentsRouter from "./assessments/index";
import geminiRouter from "./gemini/index";
import adminRouter from "./admin/index";
import customerAuthRouter from "./customer-auth/index";
import domainScanRouter from "./domain-scan/index";
import advisoriesRouter from "./advisories/index";
import kvkkRouter from "./kvkk/index";
import partnerAuthRouter from "./partner-auth/index";
import workPackagesRouter from "./work-packages/index";
import breachMonitorRouter from "./breach-monitor/index";
import toolsRouter from "./tools/index";
import tprmRouter from "./tprm/index";
import scanLeadsRouter from "./scan-leads/index";
import integrationsRouter from "./integrations/index";
import publicRouter from "./public/index";
import v1Router from "./v1/index";
import { digestRouter } from "./digest/index";
import referralRouter from "./referral/index";
import pentestLiteRouter from "./pentest-lite/index";
import healthRouter from "./health/index";
import boardReportRouter from "./board-report/index";
import aiAssessmentRouter from "./ai-assessment/index";
import aiPolicyRouter from "./ai-policy/index";
import aiMonitoringRouter from "./ai-monitoring/index";
import phishingSimRouter from "./phishing-sim/index";
import euAiActRouter from "./eu-aiact/index";
import redTeamRouter from "./red-team/index";
import deepfakeRouter from "./deepfake/index";
import docScanRouter from "./doc-scan/index";
import domainScanPurchasesRouter from "./domain-scan/purchases";
import enterpriseRouter from "./enterprise/index";
import leadGenRouter from "./lead-gen/index";
import growthEngineRouter from "./growth-engine/index";
import invoicesRouter from "./invoices/index";
import crmRouter from "./crm/index";
import adminExtrasRouter from "./admin-extras/index";

const router: IRouter = Router();

router.use(publicRouter);
router.use(v1Router);
router.use(assessmentsRouter);
router.use(geminiRouter);
router.use(adminRouter);
router.use(customerAuthRouter);
router.use(domainScanRouter);
router.use(advisoriesRouter);
router.use(kvkkRouter);
router.use(partnerAuthRouter);
router.use(workPackagesRouter);
router.use(breachMonitorRouter);
router.use(toolsRouter);
router.use(tprmRouter);
router.use(scanLeadsRouter);
router.use(integrationsRouter);
router.use("/digest", digestRouter);
router.use(referralRouter);
router.use(pentestLiteRouter);
router.use(healthRouter);
router.use(boardReportRouter);
router.use(aiAssessmentRouter);
router.use(aiPolicyRouter);
router.use(aiMonitoringRouter);
router.use(phishingSimRouter);
router.use(euAiActRouter);
router.use(redTeamRouter);
router.use(deepfakeRouter);
router.use(docScanRouter);
router.use(domainScanPurchasesRouter);
router.use(enterpriseRouter);
router.use(leadGenRouter);
router.use("/growth-engine", growthEngineRouter);
router.use(invoicesRouter);
router.use(crmRouter);
router.use(adminExtrasRouter);

export default router;
