import { Router, type Request, type Response } from "express";
import { db } from "@workspace/db";
import { domainScansTable } from "@workspace/db";
import { eq, and, or, isNull, lt, inArray } from "drizzle-orm";
import { anthropic } from "@workspace/integrations-anthropic-ai";
import { logger } from "../../lib/logger";
import type { AttackScenariosResult } from "@workspace/db";

const router = Router();

// GET /api/domain-scan/:id/attack-scenarios — cached result
router.get("/domain-scan/:id/attack-scenarios", async (req: Request, res: Response) => {
  const id = Number(req.params["id"]);
  if (!id) { res.status(400).json({ error: "Geçersiz ID" }); return; }

  const [scan] = await db.select({
    attackScenariosJson: domainScansTable.attackScenariosJson,
    attackScenariosStatus: domainScansTable.attackScenariosStatus,
  }).from(domainScansTable).where(eq(domainScansTable.id, id));

  if (!scan) { res.status(404).json({ error: "Tarama bulunamadı" }); return; }
  res.json({ status: scan.attackScenariosStatus ?? "none", result: scan.attackScenariosJson ?? null });
});

// POST /api/domain-scan/:id/attack-scenarios — trigger analysis
router.post("/domain-scan/:id/attack-scenarios", async (req: Request, res: Response) => {
  const id = Number(req.params["id"]);
  if (!id) { res.status(400).json({ error: "Geçersiz ID" }); return; }

  const [scan] = await db.select().from(domainScansTable).where(eq(domainScansTable.id, id));
  if (!scan) { res.status(404).json({ error: "Tarama bulunamadı" }); return; }

  // If complete with a cached result, return it.
  if (scan.attackScenariosStatus === "complete" && scan.attackScenariosJson) {
    res.json({ status: "complete", result: scan.attackScenariosJson });
    return;
  }

  // Atomically claim a generation slot. This only transitions the row when it is
  // not already being generated by a fresh run, which prevents concurrent POSTs
  // (e.g. mount auto-trigger + retry) from launching duplicate Claude jobs, and
  // recovers runs that got stuck in "generating" because the server restarted
  // mid-run (fire-and-forget jobs don't survive a deploy/restart).
  const claimed = await claimGeneration(id);
  res.json({ status: "generating" });
  if (claimed) {
    generateAttackScenarios(id, scan).catch(err =>
      logger.error({ err, scanId: id }, "Attack scenario generation failed")
    );
  }
});

// ─── Generation claim (compare-and-set) ───────────────────────────────────────

// Haiku is fast (~20-30s); 2 min is generous headroom for stuck-run recovery
const STALE_MS = 2 * 60 * 1000;

/**
 * Atomically transition a scan into "generating" iff it is eligible to (re)start:
 * never started, previously errored, complete-but-missing-json, or a stale
 * "generating" run whose start timestamp is older than STALE_MS (i.e. orphaned
 * by a server restart). Returns true only if this call won the claim, so the
 * caller knows whether to launch the background job.
 */
async function claimGeneration(scanId: number): Promise<boolean> {
  const staleCutoff = new Date(Date.now() - STALE_MS);
  const claimed = await db.update(domainScansTable)
    .set({ attackScenariosStatus: "generating", attackScenariosStartedAt: new Date() })
    .where(and(
      eq(domainScansTable.id, scanId),
      or(
        isNull(domainScansTable.attackScenariosStatus),
        inArray(domainScansTable.attackScenariosStatus, ["none", "error"]),
        and(eq(domainScansTable.attackScenariosStatus, "complete"), isNull(domainScansTable.attackScenariosJson)),
        and(
          eq(domainScansTable.attackScenariosStatus, "generating"),
          or(isNull(domainScansTable.attackScenariosStartedAt), lt(domainScansTable.attackScenariosStartedAt, staleCutoff)),
        ),
      ),
    ))
    .returning({ id: domainScansTable.id });
  return claimed.length > 0;
}

// ─── Auto-trigger helper (called from domain-scan route) ──────────────────────

export async function triggerAttackScenariosBackground(scanId: number, scan: typeof domainScansTable.$inferSelect): Promise<void> {
  const claimed = await claimGeneration(scanId);
  if (!claimed) return;

  generateAttackScenarios(scanId, scan).catch(err =>
    logger.error({ err, scanId }, "Attack scenario background generation failed")
  );
}

// ─── Core generation logic ────────────────────────────────────────────────────

async function generateAttackScenarios(scanId: number, scan: typeof domainScansTable.$inferSelect) {
  try {
    const prompt = buildPrompt(scan);

    const message = await anthropic.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 2000,
      messages: [{ role: "user", content: prompt }],
    });

    const block = message.content[0];
    const rawText = block?.type === "text" ? block.text.trim() : "";

    // Extract JSON from response (Claude may wrap in ```json blocks)
    const jsonMatch = rawText.match(/```json\s*([\s\S]+?)\s*```/) ?? rawText.match(/(\{[\s\S]+\})/);
    const jsonStr = jsonMatch?.[1] ?? rawText;

    const result: AttackScenariosResult = JSON.parse(jsonStr);
    result.generated_at = new Date().toISOString();

    await db.update(domainScansTable)
      .set({ attackScenariosStatus: "complete", attackScenariosJson: result })
      .where(eq(domainScansTable.id, scanId));

    logger.info({ scanId, scenarios: result.senaryolar?.length }, "Attack scenarios generated");
  } catch (err) {
    logger.error({ err, scanId }, "Attack scenario generation error");
    await db.update(domainScansTable)
      .set({ attackScenariosStatus: "error" })
      .where(eq(domainScansTable.id, scanId))
      .catch(() => null);
  }
}

function buildPrompt(scan: typeof domainScansTable.$inferSelect): string {
  const cveSummary = (scan.cveSummary as Array<{ service: string; cveId: string; description: string; cvssScore: number }> ?? []);
  const openPorts = (scan.shodanOpenPorts as Array<{ port: number; protocol: string; service: string; product: string; version: string }> ?? []);
  const shadowIt = (scan.shadowItServices as Array<{ name: string; category: string; risk: string }> ?? []);

  const criticalCves = cveSummary.filter(c => c.cvssScore >= 7.0).slice(0, 3);

  const riskFlags: string[] = [];
  if (!scan.spfPass) riskFlags.push("SPF eksik — phishing riski");
  if (!scan.dmarcPass) riskFlags.push("DMARC yok — domain spoofing");
  if (!scan.dkimPass) riskFlags.push("DKIM eksik");
  if (scan.sslDaysUntilExpiry !== null && scan.sslDaysUntilExpiry < 30) riskFlags.push(`SSL ${scan.sslDaysUntilExpiry}g içinde sona eriyor`);
  if (scan.blacklisted) riskFlags.push(`${scan.blacklistCount} kara listede`);
  if (scan.urlhausListed) riskFlags.push("URLhaus'ta kayıtlı");
  if (scan.usomListed) riskFlags.push("USOM listesinde");
  if (scan.hibpBreachCount > 0) riskFlags.push(`${scan.hibpBreachCount} veri ihlali`);
  if (scan.virusTotalMalicious > 0) riskFlags.push(`VirusTotal: ${scan.virusTotalMalicious} zararlı`);
  if (scan.httpHeadersScore < 40) riskFlags.push(`HTTP başlıkları zayıf (${scan.httpHeadersScore}/100)`);
  if ((scan.abuseIpdbScore ?? 0) > 50) riskFlags.push(`AbuseIPDB: ${scan.abuseIpdbScore}`);

  const portsSummary = openPorts.length > 0
    ? openPorts.slice(0, 5).map(p => `${p.port}/${p.protocol} ${p.service} ${p.product}`.trim()).join(", ")
    : "tespit edilmedi";

  const shadowSummary = shadowIt.length > 0
    ? shadowIt.slice(0, 4).map(s => `${s.name}(${s.risk})`).join(", ")
    : "yok";

  return `Sen kıdemli bir tehdit modelleyicisisin. Türkiye'deki bir KOBİ'nin dış güvenlik tarama sonuçlarını analiz ediyorsun.

TARAMA ÖZETİ
============
Domain: ${scan.domain} | Risk Skoru: ${scan.overallScore}/100
E-posta: SPF=${scan.spfPass ? "OK" : "FAIL"} DMARC=${scan.dmarcPass ? "OK" : "FAIL"} DKIM=${scan.dkimPass ? "OK" : "FAIL"}
SSL: ${scan.sslPass ? "Geçerli" : "Sorunlu"} (${scan.sslLabsGrade ?? "?"}) | ${scan.sslDaysUntilExpiry !== null ? `${scan.sslDaysUntilExpiry}g kaldı` : "süre bilinmiyor"}
Açık portlar: ${portsSummary}
Kritik CVE'ler: ${criticalCves.length > 0 ? criticalCves.map(c => `${c.cveId}[CVSS:${c.cvssScore}]`).join(", ") : "yok"} (toplam: ${cveSummary.length})
Kara liste: ${scan.blacklisted ? `${scan.blacklistCount} listede` : "temiz"} | URLhaus: ${scan.urlhausListed ? "kayıtlı" : "temiz"} | USOM: ${scan.usomListed ? "listede" : "temiz"}
VirusTotal: ${scan.virusTotalMalicious} zararlı | AbuseIPDB: ${scan.abuseIpdbScore ?? "N/A"}/100
HIBP ihlaller: ${scan.hibpBreachCount} | Shadow IT: ${shadowSummary}
HTTP başlıkları: ${scan.httpHeadersScore}/100 | Subdomain: ${scan.ctSubdomainCount}
Risk bayrakları: ${riskFlags.length > 0 ? riskFlags.join("; ") : "yok"}

GÖREV
=====
Bu verilerden hareketle en olası 2 saldırı senaryosunu oluştur. Her senaryo kısa ve pratik olmalı.

Sadece şu JSON'u döndür, başka metin ekleme:

{
  "risk_ozet": "1-2 cümle: en kritik güvenlik sorunu nedir?",
  "genel_tehdit_seviyesi": "Kritik|Yüksek|Orta|Düşük",
  "senaryolar": [
    {
      "baslik": "Senaryo başlığı",
      "olasilik": "Yüksek|Orta|Düşük",
      "acillik": "Acil|Yüksek|Orta",
      "giris_noktasi": "İlk erişim vektörü (1 cümle)",
      "saldiri_zinciri": [
        "1. Keşif: ...",
        "2. İlk Erişim: ...",
        "3. Yanal Hareket/Kalıcılık: ...",
        "4. Etki: ..."
      ],
      "mitre_teknikler": [
        {"kod": "T1190", "isim": "Açık Uygulama İstismarı"}
      ],
      "etki": "İş etkisi — operasyonel, finansal, itibar (1-2 cümle)",
      "kvkk_etkisi": "KVKK riski ve tahmini yaptırım (1 cümle)",
      "acil_onlemler": [
        "1. İlk önlem",
        "2. İkinci önlem"
      ]
    }
  ],
  "once_kapat": [
    {"oncelik": 1, "aksiyon": "En acil aksiyon", "neden": "Neden?"},
    {"oncelik": 2, "aksiyon": "İkinci aksiyon", "neden": "Neden?"}
  ]
}`;
}

export default router;
