import { Router, type Request, type Response } from "express";
import { db } from "@workspace/db";
import { domainScansTable } from "@workspace/db";
import { eq, and, or, isNull, lt, inArray } from "drizzle-orm";
import { anthropic } from "@workspace/integrations-anthropic-ai";
import { logger } from "../../lib/logger";
import type { AttackScenariosResult } from "@workspace/db";
import { progressBus } from "./progress-bus";

const router = Router();

// GET /api/domain-scan/:id/attack-scenarios — cached result
router.get("/domain-scan/:id/attack-scenarios", async (req: Request, res: Response) => {
  const id = Number(req.params["id"]);
  if (!id) { res.status(400).json({ error: "Geçersiz ID" }); return; }

  const [scan] = await db.select({
    attackScenariosJson: domainScansTable.attackScenariosJson,
    attackScenariosStatus: domainScansTable.attackScenariosStatus,
  }).from(domainScansTable).where(eq(domainScansTable.id, id));

  if (!scan) { res.status(404).json({ error: "Tarama bulunamadı" }); return; }
  res.json({ status: scan.attackScenariosStatus ?? "none", result: scan.attackScenariosJson ?? null });
});

// GET /api/domain-scan/:id/attack-scenarios/progress — SSE stream of progress events
router.get("/domain-scan/:id/attack-scenarios/progress", async (req: Request, res: Response) => {
  const id = Number(req.params["id"]);
  if (!id) { res.status(400).end(); return; }

  // If generation is already done, tell the client immediately so it can stop polling
  const [scan] = await db.select({
    attackScenariosStatus: domainScansTable.attackScenariosStatus,
  }).from(domainScansTable).where(eq(domainScansTable.id, id));

  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();

  if (!scan || scan.attackScenariosStatus === "complete") {
    res.write(`event: done\ndata: {}\n\n`);
    res.end();
    return;
  }

  if (scan.attackScenariosStatus === "error") {
    res.write(`event: generror\ndata: {}\n\n`);
    res.end();
    return;
  }

  const unsubscribe = progressBus.subscribe(id, res);

  const cleanup = () => {
    unsubscribe();
  };

  req.on("close", cleanup);
  req.on("aborted", cleanup);
});

// POST /api/domain-scan/:id/attack-scenarios — trigger analysis
router.post("/domain-scan/:id/attack-scenarios", async (req: Request, res: Response) => {
  const id = Number(req.params["id"]);
  if (!id) { res.status(400).json({ error: "Geçersiz ID" }); return; }

  const [scan] = await db.select().from(domainScansTable).where(eq(domainScansTable.id, id));
  if (!scan) { res.status(404).json({ error: "Tarama bulunamadı" }); return; }

  // If complete with a cached result, return it.
  if (scan.attackScenariosStatus === "complete" && scan.attackScenariosJson) {
    res.json({ status: "complete", result: scan.attackScenariosJson });
    return;
  }

  // Atomically claim a generation slot. This only transitions the row when it is
  // not already being generated by a fresh run, which prevents concurrent POSTs
  // (e.g. mount auto-trigger + retry) from launching duplicate Claude jobs, and
  // recovers runs that got stuck in "generating" because the server restarted
  // mid-run (fire-and-forget jobs don't survive a deploy/restart).
  const claimed = await claimGeneration(id);
  res.json({ status: "generating" });
  if (claimed) {
    generateAttackScenarios(id, scan).catch(err =>
      logger.error({ err, scanId: id }, "Attack scenario generation failed")
    );
  }
});

// ─── Generation claim (compare-and-set) ───────────────────────────────────────

// Haiku is fast (~20-30s); 2 min is generous headroom for stuck-run recovery
const STALE_MS = 2 * 60 * 1000;

/**
 * Atomically transition a scan into "generating" iff it is eligible to (re)start:
 * never started, previously errored, complete-but-missing-json, or a stale
 * "generating" run whose start timestamp is older than STALE_MS (i.e. orphaned
 * by a server restart). Returns true only if this call won the claim, so the
 * caller knows whether to launch the background job.
 */
async function claimGeneration(scanId: number): Promise<boolean> {
  const staleCutoff = new Date(Date.now() - STALE_MS);
  const claimed = await db.update(domainScansTable)
    .set({ attackScenariosStatus: "generating", attackScenariosStartedAt: new Date() })
    .where(and(
      eq(domainScansTable.id, scanId),
      or(
        isNull(domainScansTable.attackScenariosStatus),
        inArray(domainScansTable.attackScenariosStatus, ["none", "error"]),
        and(eq(domainScansTable.attackScenariosStatus, "complete"), isNull(domainScansTable.attackScenariosJson)),
        and(
          eq(domainScansTable.attackScenariosStatus, "generating"),
          or(isNull(domainScansTable.attackScenariosStartedAt), lt(domainScansTable.attackScenariosStartedAt, staleCutoff)),
        ),
      ),
    ))
    .returning({ id: domainScansTable.id });
  return claimed.length > 0;
}

// ─── Auto-trigger helper (called from domain-scan route) ──────────────────────

export async function triggerAttackScenariosBackground(scanId: number, scan: typeof domainScansTable.$inferSelect): Promise<void> {
  const claimed = await claimGeneration(scanId);
  if (!claimed) return;

  generateAttackScenarios(scanId, scan).catch(err =>
    logger.error({ err, scanId }, "Attack scenario background generation failed")
  );
}

// ─── Core generation logic ────────────────────────────────────────────────────

async function generateAttackScenarios(scanId: number, scan: typeof domainScansTable.$inferSelect) {
  try {
    // Milestone 1: starting up, reading scan data
    progressBus.emit(scanId, { step: 0, pct: 10, label: "Tarama verileri hazırlanıyor" });

    const prompt = buildPrompt(scan);

    // Milestone 2: prompt ready, sending to AI
    progressBus.emit(scanId, { step: 0, pct: 30, label: "Tarama verileri hazırlanıyor" });
    progressBus.emit(scanId, { step: 1, pct: 42, label: "Tehdit modeli oluşturuluyor" });

    const message = await anthropic.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 2000,
      messages: [{ role: "user", content: prompt }],
    });

    // Milestone 3: AI response received, parsing
    progressBus.emit(scanId, { step: 1, pct: 65, label: "Tehdit modeli oluşturuluyor" });

    const block = message.content[0];
    const rawText = block?.type === "text" ? block.text.trim() : "";

    // Extract JSON from response (Claude may wrap in ```json blocks)
    const jsonMatch = rawText.match(/```json\s*([\s\S]+?)\s*```/) ?? rawText.match(/(\{[\s\S]+\})/);
    const jsonStr = jsonMatch?.[1] ?? rawText;

    // Milestone 4: parsing done, saving to DB
    progressBus.emit(scanId, { step: 2, pct: 82, label: "Senaryolar yazılıyor" });

    const result: AttackScenariosResult = JSON.parse(jsonStr);
    result.generated_at = new Date().toISOString();

    // Düzeltme 3: skor-MITRE tutarlılık kontrolü
    validateReportConsistency(result, scan.overallScore ?? 50);

    await db.update(domainScansTable)
      .set({ attackScenariosStatus: "complete", attackScenariosJson: result })
      .where(eq(domainScansTable.id, scanId));

    // Milestone 5: complete — notify all SSE subscribers
    progressBus.complete(scanId);

    logger.info({ scanId, scenarios: result.senaryolar?.length }, "Attack scenarios generated");
  } catch (err) {
    logger.error({ err, scanId }, "Attack scenario generation error");
    progressBus.error(scanId);
    await db.update(domainScansTable)
      .set({ attackScenariosStatus: "error" })
      .where(eq(domainScansTable.id, scanId))
      .catch(() => null);
  }
}

// ─── Skor-MITRE tutarlılık doğrulayıcı ──────────────────────────────────────

function validateReportConsistency(result: AttackScenariosResult, overallScore: number): void {
  const level = result.genel_tehdit_seviyesi;
  if (!level) return;

  if (overallScore >= 80 && level === "Yüksek") {
    logger.warn({ score: overallScore, mitre: level }, "MITRE tehdit seviyesi skora göre çok yüksek — Düşük'e düzeltiliyor");
    result.genel_tehdit_seviyesi = "Düşük";
  } else if (overallScore >= 80 && level === "Kritik") {
    logger.warn({ score: overallScore, mitre: level }, "MITRE tehdit seviyesi skora göre çok yüksek — Orta'ya düzeltiliyor");
    result.genel_tehdit_seviyesi = "Orta";
  } else if (overallScore >= 60 && level === "Kritik") {
    logger.warn({ score: overallScore, mitre: level }, "MITRE Kritik skora göre tutarsız — Orta'ya düzeltiliyor");
    result.genel_tehdit_seviyesi = "Orta";
  }
}

function buildPrompt(scan: typeof domainScansTable.$inferSelect): string {
  const cveSummary = (scan.cveSummary as Array<{ service: string; cveId: string; description: string; cvssScore: number }> ?? []);
  const openPorts = (scan.shodanOpenPorts as Array<{ port: number; protocol: string; service: string; product: string; version: string; riskLevel?: string; riskContext?: string; isCdnExpected?: boolean }> ?? []);
  const shadowIt = (scan.shadowItServices as Array<{ name: string; category: string; risk: string }> ?? []);

  const criticalCves = cveSummary.filter(c => c.cvssScore >= 7.0).slice(0, 3);

  const riskFlags: string[] = [];
  if (!scan.spfPass) riskFlags.push("SPF eksik — phishing riski");
  if (!scan.dmarcPass) riskFlags.push("DMARC yok — domain spoofing");
  if (!scan.dkimPass) riskFlags.push("DKIM eksik");
  if (scan.sslDaysUntilExpiry !== null && scan.sslDaysUntilExpiry < 30) riskFlags.push(`SSL ${scan.sslDaysUntilExpiry}g içinde sona eriyor`);
  if (scan.blacklisted) riskFlags.push(`${scan.blacklistCount} kara listede`);
  if (scan.urlhausListed) riskFlags.push("URLhaus'ta kayıtlı");
  if (scan.usomListed) riskFlags.push("USOM listesinde");
  if (scan.hibpBreachCount > 0) riskFlags.push(`${scan.hibpBreachCount} veri ihlali`);
  if (scan.virusTotalMalicious > 0) riskFlags.push(`VirusTotal: ${scan.virusTotalMalicious} zararlı`);
  if (scan.httpHeadersScore < 40) riskFlags.push(`HTTP başlıkları zayıf (${scan.httpHeadersScore}/100)`);
  if ((scan.abuseIpdbScore ?? 0) > 50) riskFlags.push(`AbuseIPDB: ${scan.abuseIpdbScore}`);

  // Bağlama duyarlı port özeti
  const riskOrder: Record<string, number> = { critical: 4, high: 3, medium: 2, low: 1, none: 0 };
  const actualRiskPorts = openPorts.filter(p => (riskOrder[p.riskLevel ?? "low"] ?? 1) >= 2);
  const cdnExpectedPorts = openPorts.filter(p => p.isCdnExpected);
  const reviewPorts = openPorts.filter(p => p.riskLevel === "low" && !p.isCdnExpected);
  const hasCdn = cdnExpectedPorts.length > 0 && actualRiskPorts.length === 0;

  let portsSummary: string;
  if (openPorts.length === 0) {
    portsSummary = "tespit edilmedi";
  } else {
    const parts: string[] = [];
    if (actualRiskPorts.length > 0)
      parts.push(`RİSKLİ(${actualRiskPorts.map(p => `${p.port}/${p.protocol}[${p.riskLevel}]`).join(", ")})`);
    if (cdnExpectedPorts.length > 0)
      parts.push(`CDN-BEKLENEN(${cdnExpectedPorts.map(p => p.port).join(", ")})`);
    if (reviewPorts.length > 0)
      parts.push(`DOĞRULAMA-ÖNERİLEN(${reviewPorts.map(p => p.port).join(", ")})`);
    portsSummary = parts.join(" | ") || "tespit edilmedi";
  }

  const shadowHighRisk = shadowIt.filter(s => s.risk === "high" || s.risk === "yüksek").length;
  const shadowSummary = shadowIt.length > 0
    ? shadowIt.slice(0, 4).map(s => `${s.name}(${s.risk})`).join(", ")
    : "yok";

  const portContextNote = hasCdn
    ? `NOT: Tespit edilen portların tamamı CDN/proxy altyapısına ait (${scan.shodanIsp ?? "bilinmiyor"}). Bu portlar gerçek sunucuda değil CDN üzerinde görünüyor — saldırı senaryosu için CDN-bypass riski veya diğer vektörlere odaklan.`
    : "";

  // WAF bağlam notu
  const wafScan = scan as typeof scan & { wafDetected?: boolean; wafProvider?: string | null; wafBypassPossible?: boolean | null };
  const wafContextNote = wafScan.wafDetected
    ? `WAF DURUMU: ${wafScan.wafProvider ?? "Bilinmeyen"} WAF tespit edildi.
Bypass mümkün: ${wafScan.wafBypassPossible ? "EVET — kaynak sunucuya direkt erişim var, tam risk geçerli" : "Hayır — WAF aktif koruma sağlıyor"}
CVE bulgularında risk azaltıldı: ${!wafScan.wafBypassPossible ? "Evet (CVSS skorları ayarlandı)" : "Hayır (bypass riski nedeniyle)"}
WAF etkilemeyen bulgular: SSL süresi, e-posta güvenliği, HIBP sızıntıları — bunları tam kritik yaz.`
    : "WAF DURUMU: WAF tespit edilmedi. Tüm bulgular tam riskiyle raporla.";

  // Skora göre zorunlu tehdit seviyesi
  const overallScore = scan.overallScore ?? 50;
  const sslDaysLeft = scan.sslDaysUntilExpiry ?? 999;
  const mandatedThreatLevel =
    overallScore >= 80 ? "Düşük" :
    overallScore >= 60 ? "Orta" :
    overallScore >= 40 ? "Yüksek" :
    "Kritik";

  // Koşullu senaryo üretim kuralları
  const scenarioRules: string[] = [];
  if (hasCdn && shadowHighRisk === 0) {
    scenarioRules.push("CDN bypass senaryosu ÜRETME — CDN var ve yüksek riskli Shadow IT yok.");
  } else if (!hasCdn) {
    scenarioRules.push("CDN bypass senaryosu üretebilirsin — CDN tespit edilmedi, direkt sunucu erişimi söz konusu.");
  }
  if (sslDaysLeft >= 30) {
    scenarioRules.push("SSL sona erme saldırısı ÜRETME — SSL süresi yeterli (30 günden fazla kaldı).");
  } else {
    scenarioRules.push(`SSL sona erme saldırısı ÜRETEBİLİRSİN — SSL ${sslDaysLeft} gün içinde sona eriyor.`);
  }

  return `Sen kıdemli bir tehdit modelleyicisisin. Türkiye'deki bir KOBİ'nin dış güvenlik tarama sonuçlarını analiz ediyorsun.

TARAMA ÖZETİ
============
Domain: ${scan.domain} | Risk Skoru: ${overallScore}/100
E-posta: SPF=${scan.spfPass ? "OK" : "FAIL"} DMARC=${scan.dmarcPass ? "OK" : "FAIL"} DKIM=${scan.dkimPass ? "OK" : "FAIL"}
SSL: ${scan.sslPass ? "Geçerli" : "Sorunlu"} (${scan.sslLabsGrade ?? "?"}) | ${sslDaysLeft < 999 ? `${sslDaysLeft}g kaldı` : "süre bilinmiyor"}
CDN/WAF: ${wafScan.wafDetected ? (wafScan.wafProvider ?? "tespit edildi") : "tespit edilmedi"} | Shadow IT yüksek riskli: ${shadowHighRisk}
Altyapı: ${scan.shodanIsp ?? "bilinmiyor"} (${scan.shodanCountry ?? "?"})
Port analizi: ${portsSummary}${portContextNote ? `\n${portContextNote}` : ""}
${wafContextNote}
Kritik CVE'ler: ${criticalCves.length > 0 ? criticalCves.map(c => `${c.cveId}[CVSS:${c.cvssScore}]`).join(", ") : "yok"} (toplam: ${cveSummary.length})
Kara liste: ${scan.blacklisted ? `${scan.blacklistCount} listede` : "temiz"} | URLhaus: ${scan.urlhausListed ? "kayıtlı" : "temiz"} | USOM: ${scan.usomListed ? "listede" : "temiz"}
VirusTotal: ${scan.virusTotalMalicious} zararlı | AbuseIPDB: ${scan.abuseIpdbScore ?? "N/A"}/100
HIBP ihlaller: ${scan.hibpBreachCount} | Shadow IT: ${shadowSummary}
HTTP başlıkları: ${scan.httpHeadersScore}/100 | Subdomain: ${scan.ctSubdomainCount}
Risk bayrakları: ${riskFlags.length > 0 ? riskFlags.join("; ") : "yok"}

ZORUNLU KURAL — GENEL TEHDİT SEVİYESİ
======================================
Skora göre genel_tehdit_seviyesi DEĞERİ ZORUNLU OLARAK şu olmalı: "${mandatedThreatLevel}"
(Skor 80-100 → Düşük | 60-79 → Orta | 40-59 → Yüksek | 0-39 → Kritik)
Bu kurala kesinlikle uy. Senaryo ağırlığına göre değiştirme.

SENARYO ÜRETİM KURALLARI
=========================
${scenarioRules.map((r, i) => `${i + 1}. ${r}`).join("\n")}

GÖREV
=====
Bu verilerden hareketle en olası 2 saldırı senaryosunu oluştur. Her senaryo kısa ve pratik olmalı.

Sadece şu JSON'u döndür, başka metin ekleme:

{
  "risk_ozet": "1-2 cümle: en kritik güvenlik sorunu nedir?",
  "genel_tehdit_seviyesi": "Kritik|Yüksek|Orta|Düşük",
  "senaryolar": [
    {
      "baslik": "Senaryo başlığı",
      "olasilik": "Yüksek|Orta|Düşük",
      "acillik": "Acil|Yüksek|Orta",
      "giris_noktasi": "İlk erişim vektörü (1 cümle)",
      "saldiri_zinciri": [
        "1. Keşif: ...",
        "2. İlk Erişim: ...",
        "3. Yanal Hareket/Kalıcılık: ...",
        "4. Etki: ..."
      ],
      "mitre_teknikler": [
        {"kod": "T1190", "isim": "Açık Uygulama İstismarı"}
      ],
      "etki": "İş etkisi — operasyonel, finansal, itibar (1-2 cümle)",
      "kvkk_etkisi": "KVKK riski ve tahmini yaptırım (1 cümle)",
      "acil_onlemler": [
        "1. İlk önlem",
        "2. İkinci önlem"
      ]
    }
  ],
  "once_kapat": [
    {"oncelik": 1, "aksiyon": "En acil aksiyon", "neden": "Neden?"},
    {"oncelik": 2, "aksiyon": "İkinci aksiyon", "neden": "Neden?"}
  ]
}`;
}

export default router;
